routes/web.php
    Route::post('auth/register', 'Auth\AuthController@postRegister');
    Route::get('auth/register', function(){
        abort(404);
    });

    Route::post('auth/forgot-password', 'Auth\AuthController@postForgotPassword');
    Route::get('auth/forgot-password', function(){
        abort(404);
    });

    // Route::get('validate-key-forgot-password', 'Auth\AuthController@validateKeyForgotPasswword');
    // Route::post('validate-key-forgot-password', function(){
    //     abort(404);
    // });
    
    Route::post('auth/login', 'Auth\AuthController@postLogin');
    Route::get('auth/login', function(){
        abort(404);
    });

    Route::get('/auth/provider/callback', 'Auth\AuthController@postLoginProvider');
    // Route::post('login-provider', 'Auth\AuthController@postLoginProvider');
    // Route::get('login-provider', function(){
    //     abort(404);
    // });

    // Route::get('/', function(){
    //     return Hash::make('Pass4now2018!');
    // });

    Route::group(['middleware' => ['auth']], function () {
        Route::get('protected', function(){});

        Route::post('update-profile', 'Auth\AuthController@updateProfile');
        Route::get('update-profile', 'Auth\AuthController@getProfile');

        Route::post('update-info', 'Auth\AuthController@updateInfo');

        // Route::post('user/cv-status', 'CvStatusController@postCvStatus');
        // Route::get('user/cv-status', 'CvStatusController@getCvStatus');
        //Route::get('user', 'UserController@getUser');

        Route::get('/tabs/{id?}', 'CvTabController@getCvTabs');

        Route::post('/jobs', 'ApiJobsController@getJobs');
        Route::get('/job/{id}', 'ApiJobsController@getJobById');
        Route::post('/job/update', 'ApiJobsController@postUpdateJob');


        Route::get('/cvs/{id?}', 'ApiCvsController@getCvs');
        Route::post('/cv/create', 'ApiCvsController@createCV');
        Route::post('/cv/update-status/{id}', 'ApiCvsController@updateStatus');
        Route::post('/cv/active/{id}', 'ApiCvsController@activeStatus');
        Route::post('/cv/delete/{id}', 'ApiCvsController@deleteCV');
        // Route::get('user/cv-rows', 'CvRowController@getCvRowsByCvTabId');
        Route::post('/notification/get', ['as' => 'api.notification.get', 'uses' => 'NotificationController@apiGet']);
        Route::post('/notification/read', ['as' => 'api.notification.read', 'uses' => 'NotificationController@apiRead']);
        //Route::post('/tab-row-update', 'CvRowController@postUpdateCvRow');
        //Route::post('user/cv-row-delete', 'CvRowController@postDeleteCvRow');
    });
});

Route::group(['middleware' => ['web']], function () {
    // Route::get('/', 'Auth\LoginAdminController@getLoginAdmin');
     Route::get('/login', 'Auth\LoginAdminController@getLoginAdmin');
     Route::post('/login', 'Auth\LoginAdminController@postLoginAdmin');

     Route::get('/forgot-password', 'Auth\LoginAdminController@getForgotPassword');
     Route::post('/forgot-password', 'Auth\LoginAdminController@postForgotPassword');

     Route::get('/user/login', 'Auth\LoginUserController@getLogin');
     Route::post('/user/login', 'Auth\LoginUserController@postLogin');
    Route::put('/user/login', 'Auth\LoginUserController@putLogin');
     Route::post('/otp-login', 'Auth\LoginUserController@otpLogin');

    Route::get('employer/register', ['as' => 'client.employer.register', 'uses' => 'Auth\RegisterController@getRegisterEmployer']);
    Route::post('employer/register', ['as' => 'client.employer.register', 'uses' => 'Auth\RegisterController@registerEmployer']);
    Route::get('user/register', ['as' => 'client.user.register', 'uses' => 'Auth\RegisterController@getRegisterUser']);
    Route::post('user/register', ['as' => 'client.user.register', 'uses' => 'Auth\RegisterController@registerUser']);

     
     Route::get('/', 'Client\HomeController@home');
     Route::get('/xung-quanh', 'Client\HomeController@search');
     Route::get('cong-viec/{slug}', 'Client\HomeController@getJobBySlug');
     Route::get('doanh-nghiep/{slug}', 'Client\HomeController@getEmployerBySlug');
     Route::get('ho-so/{slug}', 'Client\HomeController@getUserBySlug');
     Route::get('ajax/job/search', 'Client\HomeController@getJobsSearch');
     Route::get('ajax/job/filter', 'Client\HomeController@getJobsFilter');
     Route::get('ajax/job/{id}', 'Client\HomeController@getJobById');

     Route::get('ajax/jobs', 'Client\HomeController@getJobs');
     
     Route::put('ajax/reg-cv', 'Client\HomeController@regCV');

    Route::post('/notification/get', ['as' => 'notification.get', 'uses' => 'NotificationController@get']);
    Route::post('/notification/read', ['as' => 'notification.read', 'uses' => 'NotificationController@read']);

    Route::get('/auth/{provider}', 'Auth\LoginUserController@redirectToProvider');
    Route::get('/auth/{provider}/employer', 'Auth\LoginUserController@redirectToProviderEmployer');
    Route::get('/auth/{provider}/callback', 'Auth\LoginUserController@handleProviderCallback');

    Route::group(['middleware' => ['user']], function () {
        Route::get('user/logout', 'Auth\LoginUserController@getLogout');

        Route::get('user/profile', 'Auth\LoginUserController@getProfile');
        Route::post('user/profile', 'Client\HomeController@updateProfile');

        Route::get('user/info-cv', 'Client\HomeController@getInfoCv');
        Route::post('user/info-cv', 'Client\HomeController@updateCV');


        Route::get('user/change-password', 'Auth\LoginUserController@getChangePassword');
        Route::post('user/change-password', 'Auth\LoginUserController@postChangePassword');
        
        Route::put('user/ajax/update-cv', 'Client\HomeController@updateCV');
        Route::put('user/row/delete/{id}', 'Client\HomeController@deleteRow');

        Route::put('ajax/post-cv', 'Client\HomeController@putCV');

        Route::get('user/cvs', 'Client\CvController@getCvsByUser');
        Route::put('/cv/active-status/{id}', 'Client\CvController@activeStatus');
        Route::put('user/cv/delete/{id}', 'Client\CvController@deleteCV');

        Route::put('user/review-job', 'Client\JobController@putUserReview');
    });

     Route::group(['middleware' => ['employer']], function () {

        Route::get('employer/logout', 'Auth\LoginUserController@getLogout');
        Route::get('employer/profile', 'Auth\LoginUserController@getProfile');
        Route::post('employer/profile', ['as' => 'client.employer.profile', 'uses' => 'Client\EmployerController@postEdit']);

        Route::get('employer/info-company', ['as' => 'client.employer.info_company', 'uses' => 'Client\EmployerController@getInfoCompany']);
        Route::post('employer/info-company', ['as' => 'client.employer.info_company', 'uses' => 'Client\EmployerController@postInfoCompany']);

        Route::get('employer/change-password', 'Auth\LoginUserController@getChangePassword');
        Route::post('employer/change-password', 'Auth\LoginUserController@postChangePassword');
        // Route::put('employer/ajax/update-cv', 'Client\HomeController@updateCV');
        Route::put('employer/row/delete/{id}', 'Client\HomeController@deleteRow');

        Route::post('employer/gallery-update/{id}', 'Admin\EmployersController@updateGallery');
        Route::post('employer/gallery-delete/{id}', 'Admin\EmployersController@deleteGallery');

        Route::get('employer/jobs', 'Client\JobController@getJobs');
        Route::get('employer/job/create', 'Client\JobController@getCreate');
        Route::post('employer/job/create', 'Client\JobController@postCreate')->name('empcreate');
        Route::get('employer/job/edit/{id}', 'Client\JobController@getEdit')->name('empedit');
        Route::post('employer/job/edit/{id}', 'Client\JobController@postEdit');
        Route::get('employer/job/duplicate/{id}', 'Client\JobController@getDuplicate');
        Route::put('employer/job/delete/{id}', 'Client\JobController@deleteJob');

        Route::get('ajax/job-cvs/{id}', 'Client\CvController@getCvsByJob');
        Route::put('/cv/update-status/{id}', 'Client\CvController@updateStatus');
        Route::put('employer/cv/active-status/{id}', 'Client\CvController@activeStatus');
        Route::put('employer/cv/delete/{id}', 'Client\CvController@deleteCV');
        
        Route::put('employer/review-job', 'Client\JobController@putReview');

    });

     Route::group(['middleware' => ['admin','role']], function () {

        Route::get('/logout', 'Auth\LoginAdminController@getLogoutAdmin');

        Route::get('dashboard', 'Admin\DashboardController@dashboard');

        Route::group(['middleware' => ['role']], function () {
            Route::get('tabs', 'Admin\TabsController@tabs');
            Route::get('ajax/tabs', 'Admin\TabsController@ajaxTabs');
            Route::get('tab/create', 'Admin\TabsController@getCreate');
            Route::post('tab/create', 'Admin\TabsController@postCreate');
            Route::get('tab/edit/{id}', 'Admin\TabsController@getEdit');
            Route::post('tab/edit/{id}', 'Admin\TabsController@postEdit');
            Route::post('tab/validate/{param}/{id?}', 'Admin\TabsController@postValidate');

            Route::get('utilities', 'Admin\UtilitiesController@utilities');
            Route::get('ajax/utilities', 'Admin\UtilitiesController@ajaxUtilities');
            Route::get('utilities/create', 'Admin\UtilitiesController@getCreate');
            Route::post('utilities/create', 'Admin\UtilitiesController@postCreate');
            Route::get('utilities/edit/{id}', 'Admin\UtilitiesController@getEdit');
            Route::post('utilities/edit/{id}', 'Admin\UtilitiesController@postEdit');
            Route::post('utilities/delete/{id}', 'Admin\UtilitiesController@postDelete');

            Route::get('tab/{id}/options', 'Admin\TabOptionsController@options');
            Route::get('ajax/tab/{id}/options', 'Admin\TabOptionsController@ajaxOptions');

app/CvRow.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CvRow extends Model
{
    //

    public function option(){
        return $this->belongsTo('App\TabOption', 'option_id');
    }

    public function getIconAttribute($value)
    {
        if(!empty($value))
        return config('app.api_url').$value;
    }
}

app/Job.php
<?php

namespace App;

use App\Review;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class Job extends Model
{
    //
    use Sluggable;

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'job_name'
            ]
        ];
    }

    public function employer(){
        return $this->belongsTo('App\Employer', 'employer_id');
    }
    public function employerView(){
        return $this->belongsTo('App\Employer', 'employer_view');
    }

    public function rows()
    {
        return $this->hasMany('App\CvRow', 'job_id');
    }

    public function cv(){
        return $this->hasMany('App\CV', 'job_id');
    }

    public function work_cv(){
        return $this->hasMany('App\CV', 'job_id')->where('active_work','=','1');
    }

    public function work_form(){
        return $this->belongsTo('App\WorkForm', 'job_form');
    }
    public function work_type(){
        return $this->belongsTo('App\WorkType', 'job_type');
    }

    public function star(){
        $id = $this->id;
        $star = 3;
        $count = 1;
        $reviews = Review::where('job_id','=',$id)->where('type','=','job')->get();
        if(!empty($reviews)){
            foreach ($reviews as $key => $review) {
                $star = $star + intval($review->star);
            }
            $count = $count + count($reviews);
        }
        return round($star/$count);
    }

    public function getThumbAttribute($value)
    {
        if(!empty($value)){
            return config('app.api_url').$value;
        }else{
            return $value;
        }

    }

    public function getJobDescriptionAttribute($value)
    {
        if(!empty($value)){
            $value = json_decode($value);
            $pattern = "/<a href=.*(.*?)<\/a>/";
            $value = preg_replace($pattern, "", $value);

            return json_encode($value);
        }else{
            return $value;
        }

    }

    public function getJobBenefitAttribute($value)
    {
        if(!empty($value)){
            $value = json_decode($value);
            $pattern = "/<a href=.*(.*?)<\/a>/";
            $value = preg_replace($pattern, "", $value);

            return json_encode($value);
        }else{
            return $value;
        }

    }

    public function getJobRequestAttribute($value)
    {
        if(!empty($value)){
            $value = json_decode($value);
            $pattern = "/<a href=.*(.*?)<\/a>/";
            $value = preg_replace($pattern, "", $value);

            return json_encode($value);
        }else{
            return $value;
        }

    }

    public function delete()
    {
        $this->rows()->delete();
        return parent::delete();
    }
}

resources/views/client/ajax/job.blade.php
<!-- <i class="close fas fa-times" data-dismiss="modal"></i> -->
<div class="inner">
    <div class="job-header modal-header">
        @if(!empty($job))
        <!-- <div class="bg" style="background-image:url('');"></div> -->
        <!-- <img src="{{ $job->thumb }}" alt="" class="bg"> -->
        <div class="txt">
            <div class="company">
                <div class="logo" style="background-image:url('{{ $job->employer['avatar'] }}');"></div>
                <span><a href="/doanh-nghiep/{{ $job->employer['company_slug'] }}" target="_blank">{{ $job->employer['company_name'] }}</a></span>
                <div class="rate-star">
                    <span class="active"><i class="fas fa-star"></i></span>
                    <span class="active"><i class="fas fa-star"></i></span>
                    <span class="active"><i class="fas fa-star"></i></span>
                    <span class="active"><i class="fas fa-star"></i></span>
                    <span><i class="fas fa-star"></i></span>
                </div>
            </div>
            <h5 class="modal-title"><a href="/cong-viec/{{ $job->slug }}" target="_blank">{{ $job->job_name }}</a></h5>
            
            <span class="job_address">{{ $job->job_address?$job->job_address:'' }}</span>
            
            @if($job->job_wage)
            <div class="salary">
                <span>Mức lương</span>
                <h4 class="parse-price">{{ $job->job_wage?$job->job_wage:'' }}</h4>
            </div>
            @endif
        </div>
        @endif
    </div>
    <div class="job-content modal-body">
        @if(!empty($job))
        <div class="blk-info type-flex">
                        <!-- <h4 class="blk-title">Thông tin công việc</h4> -->
                        <div class="listing">
                            @if($job->work_form)
                            <li class="item">
                                <div class="left-obj">
                                    <span>Hình thức</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->work_form?$job->work_form['name']:'...' }}</p>
                                </div>
                            </li>
                            @endif
                            @if($job->job_type)
                            <li class="item">
                                <div class="left-obj">
                                    <span>Loại hình</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->work_type?$job->work_type['name']:'...' }}</p>
                                </div>
                            </li>
                            @endif
                            @if($job->job_city)
                            <!-- <li class="item">
                                <div class="left-obj">
                                    <span>Tỉnh/Thành Phố</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->job_city?$job->job_city:'...' }}</p>
                                </div>
                            </li> -->
                            @endif
                            @if($job->job_time)
                            <!-- <li class="item">
                                <div class="left-obj">
                                    <span>Thời gian làm việc</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->job_time?$job->job_time:'...' }}</p>
                                </div>
                            </li> -->
                            @endif
                            @if($job->job_date_start)
                            <!-- <li class="item">
                                <div class="left-obj">
                                    <span>Ngày bắt đầu</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->job_date_start?$job->job_date_start:'...' }}</p>
                                </div>
                            </li> -->
                            @endif
                            @if($job->job_gender)
                            <!-- <li class="item">
                                <div class="left-obj">
                                    <span>Giới tính</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ ($job->job_gender == 3)?'Nam hoặc nữ':'' }}{{ ($job->job_gender == 1)?'Nam':'' }}{{ ( $job->job_gender == 2)?'Nữ':'' }}</p>
                                </div>
                            </li> -->
                            @endif
                            @if($job->job_age)
                            <!-- <li class="item">
                                <div class="left-obj">
                                    <span>Độ tuổi</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->job_age?$job->job_age:'...' }}</p>
                                </div>
                            </li> -->
                            @endif
                            @if($job->job_people)
                            <li class="item">
                                <div class="left-obj">
                                    <span>Số lượng</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->job_people?$job->job_people:'...' }}</p>
                                </div>
                            </li>
                            @endif
                            @if($job->job_end_cv)
                            <!-- <li class="item">
                                <div class="left-obj">
                                    <span>Hạn nộp hồ sơ</span>
                                </div>
                                <div class="right-obj">
                                    <p>{{ $job->job_end_cv?$job->job_end_cv:'...' }}</p>
                                </div>
                            </li> -->
                            @endif
                            
                        </div>
                    </div>
        <div class="blk-info no-box">
            <div class="blk">
                <h5>MÔ TẢ CÔNG VIỆC</h5>
                <article>
                    {!! json_decode($job->job_description) !!}
                </article>    
            </div>
            @if(!empty($job->job_benefit))
            <div class="blk">
                <h5>QUYỀN LỢI</h5>
                @if(!empty($utilities))
                    <div class="utility-list">
                        <ul>
                        @foreach($utilities as $utility)
                            <li class="item"><i class="fas fa-check-circle"></i> {{ $utility->name }}</li>
                        @endforeach
                        </ul>
                    </div>
                @endif
                <article>
                    {!! json_decode($job->job_benefit) !!}
                </article>
            </div>
            @endif
            @if(!empty($job->job_request))
            <div class="blk">
                <h5>YÊU CẦU</h5>
                <article>
                    {!! json_decode($job->job_request) !!}
                </article>
            </div>
            @endif
        </div>
        @if($tabs)
        @foreach($tabs as $tab)
        @if($tab->rows->count())
        <!-- <div class="blk-info">
            <h4 class="blk-title">Yêu cầu {{ $tab->name }}</h4>
            <div class="listing">
            @foreach($tab->rows as $row)
            @if(!empty($tab->input_type) && (($tab->input_type == "select" && $row->option) || ($tab->input_type == "text" && !$row->option)))
                <li class="item">
                @if($tab->input_type == "text")
                    <div class="thumbnail" style="background-image: url('{{ $row->icon }}')"></div>
                @endif
                @if($tab->input_type == "select")
                    <div class="thumbnail" style="background-image: url('{{ $row->option['icon'] }}')"></div>
                @endif
                    <div class="meta">
                        <h5>{{ ($tab->input_type == "text")?$row->name:"" }}{{ ($tab->input_type == "select")?$row->option['name']:"" }}</h5>
                        <span>{{ $row->description }}</span>
                        <p>{{ $row->date_start }}{{ (!empty($row->date_end))?" - ".$row->date_end:"" }}</p>
                    </div>
                </li>
            @endif
            @endforeach
            </div>
        </div> -->
        @endif
        @endforeach
        @endif
        @endif
    </div>
</div>
<div class="job-action modal-footer">
    @if(!empty($job) && Auth::guest()) 
    <button type="button" class="btn btn-primary btn-post-cv" job-id="{{ $job->id }}" {{ (!empty($job->cv_active))?'disabled="disabled"':'' }} >{{ (!empty($job->cv_active))?'Bạn đã nộp cv':'Nộp CV' }}</button>
    @endif
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
</div>
<script type="text/javascript">
    window.history.pushState({}, '', '/cong-viec/{{ $job->slug }}');
</script>

resources/views/client/ajax/jobSearch.blade.php
@if(!empty($jobs))
@foreach($jobs as $job)
@if(empty($employer))
<div class="job-item {{ (!empty($type) && $type=='box')?'':'' }}" job-id="{{ $job->id }}" job-lat="{{ $job->lat }}" job-lng="{{ $job->lng }}" job-wage="{{ $job->job_wage }}" >
    <div class="profile">
        <div class="thumbnail" style="background-image: url('{{ $job->employer['avatar'] }}')"></div>
        <div class="rate-star" >
            @for ($i = 1; $i < 6; $i++)
                <span class="item {{ ($i <= $job->star())?'active':'' }}"><i class="fas fa-star"></i></span>
            @endfor
        </div>
        <span class="point">{{ $job->star() }}</span>
    </div>
    <div class="detail">
        <span class="job-owner"><i class="fas fa-building"></i> {{ $job->employer['company_name'] }}</span>
        <span class="job-name">{{ $job->job_name }}</span>
        <div class="meta">
            <ul>
                <li class="info-location" data-toggle="tooltip" data-placement="top" title="Địa điểm làm việc"><i class="fas fa-location-arrow"></i> {{ !empty($job->job_address)?$job->job_address:'' }}</li>
                <li class="info-job_form" data-toggle="tooltip" data-placement="top" title="Hình thức làm việc"><i class="fas fa-briefcase"></i> <span>{{ $job->work_form?$job->work_form['name']:'...' }}</span></li>
                <li class="info-salary " data-toggle="tooltip" data-placement="top" title="Mức lương"><i class="fas fa-coins"></i> <span class="parse-price">{{ $job->job_wage?$job->job_wage:'' }}</span></li>
            </ul>   
        </div>
        <div class="desc">
            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur dolorum magnam maiores doloremque, maxime facere quisquam.</p> -->
            <p>{!! str_limit(strip_tags(json_decode($job->job_description)), $limit = 150, $end = '...') !!}</p>
        </div>
        <div class="status">
            <ul>
                <li class="total-number" data-toggle="tooltip" data-placement="top" title="Số lượng yêu cầu"><i class="fas fa-users"></i> {{ !empty($job->job_people)?$job->job_people:0 }}</li>
                <li data-toggle="tooltip" data-placement="top" title="Đã nộp CV"><i class="fas fa-file-alt"></i> {{ !empty($job->cv)?count($job->cv):0 }}</li>
                <li data-toggle="tooltip" data-placement="top" title="Đã làm việc"><i class="fas fa-handshake"></i> {{ !empty($job->work_cv)?count($job->work_cv):0 }}</li>
            </ul>
        </div>
        <div class="action">
            <span class="btn btn-primary">Ứng tuyển ngay</span>
        </div>
    </div>
</div>
@else
<div class="job-item" job-id="{{ $job->id }}" job-lat="{{ $job->lat }}" job-lng="{{ $job->lng }}" job-wage="{{ $job->job_wage }}">
    <!-- <div class="thumbnail" style="background-image: url('{{ $job->employer['avatar'] }}')"></div> -->
    <div class="detail">
        <span class="job-name">{{ $job->job_name }}</span>
        <div class="meta">
            <ul>
                <li class="info-location" data-toggle="tooltip" data-placement="top" title="Địa điểm làm việc"><i class="fas fa-location-arrow"></i> {{ !empty($job->job_address)?$job->job_address:$job->employer['company_address'] }}</li>
                <li class="info-salary" data-toggle="tooltip" data-placement="top" title="Mức lương"><i class="fas fa-coins"></i> <span class="parse-price">{{ $job->job_wage?$job->job_wage:'' }}</span></li>
            </ul> 
        </div>
        <div class="status">
            <ul>
                <li class="total-number" data-toggle="tooltip" data-placement="top" title="Số lượng yêu cầu"><i class="fas fa-users"></i> {{ !empty($job->job_people)?$job->job_people:0 }}</li>
                <li data-toggle="tooltip" data-placement="top" title="Đã nộp CV"><i class="fas fa-file-alt"></i> {{ !empty($job->cv)?count($job->cv):0 }}</li>
                <li data-toggle="tooltip" data-placement="top" title="Đã làm việc"><i class="fas fa-handshake"></i> {{ !empty($job->work_cv)?count($job->work_cv):0 }}</li>
            </ul>
        </div>
    </div>
</div>
@endif
@endforeach
@endif
<input type="hidden" id="totalJob" value="{{ !empty($totalJob)?$totalJob:'' }}">